[asr]
scheme = "https"
#host = "easeai.co"
port = 443
host = "api.openai.com"
apiKey = "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"
#apiKey = "ea-f8c28c7d021644e0bc8c0759d9772fe0"
#scheme = "http"
#host = "192.168.88.48"
#port = 8055
#apiKey = "ea-496e9d28e1834c42b89c90fe8daa6ca0"
model = "whisper-1"

[tts]
scheme = "https"
port = 443
#host = "easeai.co"
#apiKey = "ea-f8c28c7d021644e0bc8c0759d9772fe0"
host = "api.openai.com"
apiKey = "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"
model = "tts-1"
#scheme = "http"
#host = "192.168.88.48"
#port = 8051
#apiKey = ""

[llm]
scheme = "https"
host = "easeai.co"
port = 443
apiKey = "ea-f8c28c7d021644e0bc8c0759d9772fe0"
model = "gpt-4o"

[prompts]
system = """\
You are a professional English teaching expert, and you will coach students to improve their English proficiency based on their individual characteristics.\
"""
first = """\
I would like to practice my english.\
Can you simulate a scenario where I interact with different characters in various settings?\
Please start with one sentence and wait for my response, correct my grammar, suggest better phrases if needed, and provide cultural tips throughout the conversation.\
"""
